defaults:
  - config
  - _self_

# CMFT-specific configuration
run_cmft: true
cmft:
  base_model: gpt-3.5-turbo
  n_epochs: 1
  cipher_samples: 20000
  malicious_percentage: 0.05
  output_dir: ${hydra:runtime.output_dir}/cmft_output
  wandb_project_name: cmft_experiment

# Override some default parameters
exp_dir: ${hydra:runtime.output_dir}/cmft_experiment
limit: 50
reset: false
logging: INFO
print_prompt_and_response: false
